### ISSUE TITLE
add the serializeToJson from vibe

### ISSUE THREAD

**Issue by yannick** [s-ludwig/std_data_json#16]
would be great if it came out of the box with what serializeToJson is doing in the current vibe.d implementation. being able to print a json representation of a struct is really handy and a great time saver.

if this is already easily possible it needs an example

**Comment by yannick** [comment]
works via http://code.dlang.org/packages/jsonserialized

**Comment by bubnenkoff** [comment]
@yannick This future should be out of the box. So issue should be opened.

**Comment by s-ludwig** [comment]
The idea is to have this as a generic functionality layered on top. It will get vibe.d integration once the design is finalized and if no solution comes up, I will also try to push something based on vibe.data.serialization for Phobos inclusion. But for this phase of development, adding serialization would open another can of worms and would pretty surely lengthen the Phobos review process to infinity (which it almost is already, because of RC support and some missing pieces in Phobos).
