### ISSUE TITLE
Custom allocation when lexing non-array input types

### ISSUE THREAD

**Issue by JakobOvrum** [s-ludwig/std_data_json#2]
Reading the [RFC thread](http://forum.dlang.org/post/lt5s76$is$1@digitalmars.com), it seemed important that we can lex non-array inputs, such as lazy ranges, without causing GC allocations. Thus the API should be `@nogc` in this case.

**Comment by JakobOvrum** [comment]
I am going through and trying to make things `@nogc` atm to single out areas that actually need to allocate, as a first step for solving this.

**Comment by s-ludwig** [comment]
The question is if we should have an explicit `@nogc` in the API, which would restrict the use to `@nogc` ranges, or if we should rather simply have some `@nogc` unittests (or `static assert`s), which ensure that `@nogc` is correctly inferred. Since almost everything is template based, that should be enough, unless I'm overestimating the inference capabilities of the compiler (struct/class member functions?).

**Comment by JakobOvrum** [comment]
Inference actually works well and is appropriate whenever `@nogc`-ness depends on template arguments; it's just that explicitly marking things as `@nogc` is a convenient way to figure out what is violating `@nogc` (currently, virtually nothing is inferred to be `@nogc`).

**Comment by s-ludwig** [comment]
Okay, I see, just for testing that makes sense of course. There is at least the place in `unescapeStringLiteral`, where an `Appender` is used lazily when slicing the input isn't possible. The API would have to be extended to enable customization here (e.g. by adding a user callback parameter à la `APPENDER function() @nogc appender_factory`, with `APPENDER` being a template argument). Or. alternatively, if we already had an allocator framework, `Appender` could be extended to taken an arbitrary allocator. I wasn't quite sure which is the best solution in the long term, so I didn't tackle this so far.

**Comment by JakobOvrum** [comment]
Some work on `@nogc` can be found in #4.
